### ISSUE TITLE
exomiser prioritization broken for some genes

### ISSUE THREAD

**Issue by stolpeo** [bihealth/varfish-server#1085]
```
Traceback (most recent call last):
   File "/usr/src/app/variants/models/jobs.py", line 189, in run_query_bg_job
     _inner()
   File "/usr/src/app/variants/models/jobs.py", line 173, in _inner
     for batch in batched(
  File "/usr/src/app/variants/models/jobs.py", line 36, in batched
     batch = list(islice(it, n))
   File "/usr/src/app/variants/models/jobs.py", line 113, in _read_records
     payload["phenotype_score"] = phenotype_scores[line.entrez_id]
 KeyError: '83642'
```

**Comment by stolpeo** [comment]
**RCA**
The genes are properly scored. Some of the genes of the variants have no corresponding entrez id in the results of the exomiser.

**Resolution proposal**
Return `None` if the entrez id can't be looked up.
