### ISSUE TITLE
Bug in refresh_individual_sex_affected

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#686]
**Describe the bug**
The command introduced in the resolution of #158 can crash.

**To Reproduce**
```
# python /usr/src/app/manage.py refresh_individuals
Refreshing all clinvar_xml individuals
Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/clinvar_export/management/commands/refresh_individuals.py", line 15, in handle
    refresh_individual_sex_affected()
  File "/usr/src/app/clinvar_export/models.py", line 405, in refresh_individual_sex_affected
    related_ped_entry = ped_entries[individual.name]
KeyError: '<REDACTED>'
```

**Expected behavior**
In this case, only a warning should be printed.

**Additional context**
N/A

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
The assumption that the individual must be in the pedigree is wrong.

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Check the existence of the individual in the Python dict. Print warning if it does not exist any more.

**Affected Components**
VarFish server

**Affected Modules/Files**
`clinvar_export/models.py`

**Required Architectural Changes**
None

**Required Database Changes**
None

**Backport Possible?**
Yes

**Resolution Sketch**
See above.
