### ISSUE TITLE
[variants/vueapp] npm run build fails with failed import

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#718]
**Describe the bug**
When running build on the variants vueapp the build fails with a rollup error.

**To Reproduce**

1. cd `variants/vueapp`
2. `npm run build`

**Actual behavior**

```
[vite]: Rollup failed to resolve import "/icons/mdi/refresh.svg" from "src/components/SmallVariantFilterForm.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "/icons/mdi/refresh.svg" from "src/components/SmallVariantFilterForm.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/max/Git/varfish-server/variants/vueapp/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:41772:19)
    at onwarn (/home/max/Git/varfish-server/variants/vueapp/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:41588:13)
    at Object.onwarn (/home/max/Git/varfish-server/variants/vueapp/node_modules/rollup/dist/shared/rollup.js:23226:13)
    at ModuleLoader.handleResolveId (/home/max/Git/varfish-server/variants/vueapp/node_modules/rollup/dist/shared/rollup.js:22510:26)
    at /home/max/Git/varfish-server/variants/vueapp/node_modules/rollup/dist/shared/rollup.js:22471:26
```

**Comment by xiamaz** [comment]
`mdi/refresh.svg` seems to be an material design icon. In the rest of the vueapp project these are handled through a library. Is this an oversight or is the manual src needed here:

```
                <img
                  class="img-light"
                  :class="{
                    spin:
                      store.queryState === QueryStates.Fetching.value ||
                      store.queryState === QueryStates.Running.value,
                  }"
                  src="/icons/mdi/refresh.svg"
                />

```
